"""SQLAlchemy persistence models for the W2 domain."""

from w2.infrastructure.persistence.models import (
    AuditEventModel,
    BookmakerModel,
    CompetitionModel,
    DataProvenanceModel,
    FeatureSnapshotModel,
    FixtureModel,
    InjuryModel,
    LineupModel,
    MarketModel,
    ModelRunModel,
    OddsObservationModel,
    PlayerModel,
    PredictionModel,
    ProviderEntityMappingModel,
    RawPayloadReferenceModel,
    RecommendationLockModel,
    RecommendationModel,
    RefereeModel,
    ResultModel,
    SeasonModel,
    SettlementModel,
    SquadModel,
    StageModel,
    SuspensionModel,
    TeamModel,
    TeamRatingModel,
    VenueModel,
    WeatherObservationModel,
)

__all__ = [
    "AuditEventModel",
    "BookmakerModel",
    "CompetitionModel",
    "DataProvenanceModel",
    "FeatureSnapshotModel",
    "FixtureModel",
    "InjuryModel",
    "LineupModel",
    "MarketModel",
    "ModelRunModel",
    "OddsObservationModel",
    "PlayerModel",
    "PredictionModel",
    "ProviderEntityMappingModel",
    "RawPayloadReferenceModel",
    "RecommendationLockModel",
    "RecommendationModel",
    "RefereeModel",
    "ResultModel",
    "SeasonModel",
    "SettlementModel",
    "SquadModel",
    "StageModel",
    "SuspensionModel",
    "TeamModel",
    "TeamRatingModel",
    "VenueModel",
    "WeatherObservationModel",
]

