from __future__ import annotations

from enum import StrEnum


class DataLayer(StrEnum):
    RAW = "RAW"
    NORMALIZED = "NORMALIZED"
    FEATURE = "FEATURE"
    PREDICTION_STRATEGY = "PREDICTION_STRATEGY"


class MarketType(StrEnum):
    ONE_X_TWO = "ONE_X_TWO"
    ASIAN_HANDICAP = "ASIAN_HANDICAP"
    TOTALS = "TOTALS"
    BTTS = "BTTS"


class DecisionTier(StrEnum):
    NOT_READY = "NOT_READY"
    SKIP = "SKIP"
    WATCH = "WATCH"
    ANALYSIS_PICK = "ANALYSIS_PICK"
    RECOMMEND = "RECOMMEND"


class ProbabilitySource(StrEnum):
    MARKET_DEVIG = "MARKET_DEVIG"
    MODEL_FALLBACK = "MODEL_FALLBACK"
    UNKNOWN = "UNKNOWN"


class DataStatus(StrEnum):
    READY = "READY"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    BLOCKED = "BLOCKED"


class LifecycleStatus(StrEnum):
    DRAFT = "DRAFT"
    LOCKED = "LOCKED"
    SUPERSEDED = "SUPERSEDED"
    VOID = "VOID"
    SETTLED = "SETTLED"


class DecisionReasonCode(StrEnum):
    DATA_MISSING_XG = "DATA_MISSING_XG"
    DATA_STALE_ODDS = "DATA_STALE_ODDS"
    LINEUPS_PENDING = "LINEUPS_PENDING"
    MARKET_UNAVAILABLE = "MARKET_UNAVAILABLE"
    EDGE_INSUFFICIENT = "EDGE_INSUFFICIENT"
    PROVIDER_BUDGET_EXHAUSTED = "PROVIDER_BUDGET_EXHAUSTED"
    CONTRADICTION_UNEXPLAINED = "CONTRADICTION_UNEXPLAINED"
    COVERAGE_NONE = "COVERAGE_NONE"
    FIXTURE_LIVE_OR_FINISHED = "FIXTURE_LIVE_OR_FINISHED"


class SettlementOutcome(StrEnum):
    WIN = "WIN"
    HALF_WIN = "HALF_WIN"
    PUSH = "PUSH"
    HALF_LOSS = "HALF_LOSS"
    LOSS = "LOSS"


class RecommendationStatus(StrEnum):
    DRAFT = "DRAFT"
    LOCKED = "LOCKED"


class FixtureStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    LIVE = "LIVE"
    FINISHED = "FINISHED"
    POSTPONED = "POSTPONED"
    CANCELLED = "CANCELLED"


class Side(StrEnum):
    HOME = "HOME"
    AWAY = "AWAY"
