import type { DashboardV2FixtureModel, DashboardV2ViewModel } from "./dashboard-v2-model";

const ready = (
  fixture: Omit<DashboardV2FixtureModel, "decisionTier" | "dataStatus" | "reasonLabel" | "modelLabel" | "calibrationLabel" | "dataFacts" | "tracking">,
): DashboardV2FixtureModel => ({
  ...fixture,
  decisionTier: "ANALYSIS_PICK",
  dataStatus: "READY",
  reasonLabel: null,
  modelLabel: "精确 DC-Poisson",
  calibrationLabel: "基线先验模型 · 尚未完成正式校准验证",
  dataFacts: ["盘口身份完整", "真实 xG 已就绪", "内部评级已就绪", "首发未到采集时点"],
  tracking: {
    status: "CAPTURED_PENDING",
    label: "验证 ledger 已记录",
    detail: "待完场结算",
    captureHash: "8aab83c4d7f8",
  },
});

const quiet = (
  fixture: Omit<DashboardV2FixtureModel, "decisionTier" | "dataStatus" | "reasonLabel" | "modelLabel" | "calibrationLabel" | "dataFacts" | "tracking">,
  decisionTier: "NO_EDGE" | "WATCH" | "NOT_READY" | "SKIP",
  reasonLabel: string,
  dataStatus: "READY" | "PARTIAL" | "STALE" | "BLOCKED" = "READY",
): DashboardV2FixtureModel => ({
  ...fixture,
  decisionTier,
  dataStatus,
  reasonLabel,
  modelLabel: "精确 DC-Poisson",
  calibrationLabel: "基线先验模型 · 尚未完成正式校准验证",
  dataFacts: ["真实赛程", "只读分析", reasonLabel],
  tracking: {
    status: "NOT_CAPTURED",
    label: "本场未进入验证分母",
    detail: decisionTier === "NO_EDGE" ? "优势不足，保留为影子证据" : reasonLabel,
  },
});

export const dashboardV2ReferenceFixture: DashboardV2ViewModel = {
  observedFootballDay: "2026-07-21",
  release: {
    environment: "staging",
    apiSha: "d377d6e",
    webSha: "d377d6e",
    pageUpdatedAt: "2026-07-21T12:33:00Z",
    oddsConfirmedAt: "2026-07-21T10:59:43Z",
    nextRefreshAt: null,
  },
  ledger: {
    rangeLabel: "07-07 至 07-21",
    validationCount: 26,
    settledCount: 23,
    pendingCount: 3,
    eligibleCount: 16,
    evidenceRepairPendingCount: 7,
    hitCount: 11,
    missCount: 3,
    pushCount: 2,
    voidCount: 0,
    decisiveCount: 14,
    hitRate: 11 / 14,
    clvMedian: 0.01,
    clvSampleCount: 2,
  },
  health: {
    automaticCollectionPaused: true,
    competitionCount: 4,
    upcomingCount: 15,
    description: "当前显示最近冻结快照；下一次受控采集尚未安排。",
  },
  selectedFixtureId: "1494218",
  fixtures: [
    ready({
      fixtureId: "1494218",
      kickoffUtc: "2026-07-25T13:00:00Z",
      status: "NS",
      competition: "瑞典超 · 常规赛第14轮",
      homeTeam: "代格福什",
      awayTeam: "尤尔加登",
      nextEvaluationAt: null,
      primaryMarketLabel: "让球 · 客队 -0.75 @1.90",
      secondaryMarketLabel: "大小球 · 小 3.5 @1.98",
      scorelineSummary: "0-1 · 0-2 · 1-2",
      quote: {
        marketPolicyLabel: "多庄共识主线",
        bookmaker: "Betano",
        capturedAt: "2026-07-21T10:59:43Z",
        marketLabel: "让球",
        selectionLabel: "客队",
        line: "-0.75",
        odds: 1.9,
        marketProbability: 0.4974,
        modelProbability: 0.6212,
        probabilityDelta: 0.1238,
        expectedValue: 0.1624,
        uncertainty: 0.0438,
      },
      scorelineProjection: {
        status: "READY",
        simulationsRequested: 10000,
        simulationsCompleted: 10000,
        consistentSampleCount: 4862,
        consistencyLabel: "全部符合：客队 -0.75 · 次推小 3.5",
        decisionHash: "4d37be82e2fe148f0b67d3a7eac02f6c89bf02f3",
        evidenceHash: "efbf53d8b4c2f668c1cd52d3a2484fa6d0f3d650",
        top3: [
          { scoreline: "0-1", sampleCount: 1082, unconditionalProbability: 0.1082, conditionalProbability: 0.2225, primarySettlement: "HALF_WIN" },
          { scoreline: "0-2", sampleCount: 948, unconditionalProbability: 0.0948, conditionalProbability: 0.1950, primarySettlement: "WIN" },
          { scoreline: "1-2", sampleCount: 891, unconditionalProbability: 0.0891, conditionalProbability: 0.1833, primarySettlement: "HALF_WIN" },
        ],
      },
    }),
    ready({
      fixtureId: "1494220",
      kickoffUtc: "2026-07-25T12:00:00Z",
      status: "NS",
      competition: "瑞典超 · 常规赛第14轮",
      homeTeam: "天狼星",
      awayTeam: "哥德堡",
      nextEvaluationAt: "2026-07-25T10:30:00Z",
      primaryMarketLabel: "大小球 · 小 3.5 @1.88",
      secondaryMarketLabel: null,
      scorelineSummary: "1-1 · 1-0 · 2-0",
      quote: {
        marketPolicyLabel: "多庄共识主线",
        bookmaker: "Unibet",
        capturedAt: "2026-07-21T10:59:43Z",
        marketLabel: "大小球",
        selectionLabel: "小",
        line: "3.5",
        odds: 1.88,
        marketProbability: 0.5319,
        modelProbability: 0.6485,
        probabilityDelta: 0.1166,
        expectedValue: 0.2192,
        uncertainty: 0.0391,
      },
      scorelineProjection: {
        status: "READY",
        simulationsRequested: 10000,
        simulationsCompleted: 10000,
        consistentSampleCount: 6485,
        consistencyLabel: "全部符合：小 3.5",
        decisionHash: "a5e7a133de7c2a489f945641e8a4108ec95abdf8",
        evidenceHash: "ebdcd9bf649d429e472264d829e2ccbd83fe6d95",
        top3: [
          { scoreline: "1-1", sampleCount: 1134, unconditionalProbability: 0.1134, conditionalProbability: 0.1749, primarySettlement: "WIN" },
          { scoreline: "1-0", sampleCount: 1011, unconditionalProbability: 0.1011, conditionalProbability: 0.1559, primarySettlement: "WIN" },
          { scoreline: "2-0", sampleCount: 892, unconditionalProbability: 0.0892, conditionalProbability: 0.1375, primarySettlement: "WIN" },
        ],
      },
    }),
    ready({
      fixtureId: "1494219",
      kickoffUtc: "2026-07-25T12:00:00Z",
      status: "NS",
      competition: "瑞典超 · 常规赛第14轮",
      homeTeam: "布洛马波卡纳",
      awayTeam: "哈马比",
      nextEvaluationAt: null,
      primaryMarketLabel: "大小球 · 大 2.5 @1.86",
      secondaryMarketLabel: null,
      scorelineSummary: "1-2 · 2-1 · 2-2",
      quote: {
        marketPolicyLabel: "多庄共识主线",
        bookmaker: "Bet365",
        capturedAt: "2026-07-21T11:00:03Z",
        marketLabel: "大小球",
        selectionLabel: "大",
        line: "2.5",
        odds: 1.86,
        marketProbability: 0.5376,
        modelProbability: 0.6252,
        probabilityDelta: 0.0876,
        expectedValue: 0.1629,
        uncertainty: 0.0412,
      },
      scorelineProjection: {
        status: "READY",
        simulationsRequested: 10000,
        simulationsCompleted: 10000,
        consistentSampleCount: 6252,
        consistencyLabel: "全部符合：大 2.5",
        decisionHash: "d16a3ca7f1713ec65c226597c08918d67c6b4411",
        evidenceHash: "baf78adca3178e6065aa688801c095adf2dd70a9",
        top3: [
          { scoreline: "1-2", sampleCount: 964, unconditionalProbability: 0.0964, conditionalProbability: 0.1542, primarySettlement: "WIN" },
          { scoreline: "2-1", sampleCount: 901, unconditionalProbability: 0.0901, conditionalProbability: 0.1441, primarySettlement: "WIN" },
          { scoreline: "2-2", sampleCount: 773, unconditionalProbability: 0.0773, conditionalProbability: 0.1236, primarySettlement: "WIN" },
        ],
      },
    }),
    ready({
      fixtureId: "1494222",
      kickoffUtc: "2026-07-26T14:30:00Z",
      status: "NS",
      competition: "瑞典超 · 常规赛第14轮",
      homeTeam: "马尔默",
      awayTeam: "埃尔夫斯堡",
      nextEvaluationAt: null,
      primaryMarketLabel: "让球 · 主队 -0.25 @1.91",
      secondaryMarketLabel: "大小球 · 大 2.5 @1.84",
      scorelineSummary: "2-1 · 3-1 · 3-2",
      quote: {
        marketPolicyLabel: "多庄共识主线",
        bookmaker: "Pinnacle",
        capturedAt: "2026-07-21T11:00:11Z",
        marketLabel: "让球",
        selectionLabel: "主队",
        line: "-0.25",
        odds: 1.91,
        marketProbability: 0.4979,
        modelProbability: 0.5872,
        probabilityDelta: 0.0893,
        expectedValue: 0.1213,
        uncertainty: 0.0364,
      },
      scorelineProjection: {
        status: "READY",
        simulationsRequested: 10000,
        simulationsCompleted: 10000,
        consistentSampleCount: 3798,
        consistencyLabel: "全部符合：主队 -0.25 · 次推大 2.5",
        decisionHash: "de06c8f4893db18f9cf9d3d7787a0db9466fd53f",
        evidenceHash: "7c6a036e8976be6f95989666aa4faf7ec4c3114c",
        top3: [
          { scoreline: "2-1", sampleCount: 804, unconditionalProbability: 0.0804, conditionalProbability: 0.2117, primarySettlement: "WIN" },
          { scoreline: "3-1", sampleCount: 616, unconditionalProbability: 0.0616, conditionalProbability: 0.1622, primarySettlement: "WIN" },
          { scoreline: "3-2", sampleCount: 523, unconditionalProbability: 0.0523, conditionalProbability: 0.1377, primarySettlement: "WIN" },
        ],
      },
    }),
    ready({
      fixtureId: "1494223",
      kickoffUtc: "2026-07-26T17:00:00Z",
      status: "NS",
      competition: "瑞典超 · 常规赛第14轮",
      homeTeam: "赫根",
      awayTeam: "AIK Stockholm",
      nextEvaluationAt: null,
      primaryMarketLabel: "大小球 · 小 3.5 @1.92",
      secondaryMarketLabel: null,
      scorelineSummary: "1-1 · 1-0 · 0-1",
      quote: {
        marketPolicyLabel: "多庄共识主线",
        bookmaker: "Betano",
        capturedAt: "2026-07-21T11:00:14Z",
        marketLabel: "大小球",
        selectionLabel: "小",
        line: "3.5",
        odds: 1.92,
        marketProbability: 0.5095,
        modelProbability: 0.6031,
        probabilityDelta: 0.0936,
        expectedValue: 0.1580,
        uncertainty: 0.0409,
      },
      scorelineProjection: {
        status: "READY",
        simulationsRequested: 10000,
        simulationsCompleted: 10000,
        consistentSampleCount: 6031,
        consistencyLabel: "全部符合：小 3.5",
        decisionHash: "cc21f802b2431ce8f86051f45a88654ffbb0429a",
        evidenceHash: "230388e53ceef5f31bf0aac6a04e861189206547",
        top3: [
          { scoreline: "1-1", sampleCount: 1037, unconditionalProbability: 0.1037, conditionalProbability: 0.1719, primarySettlement: "WIN" },
          { scoreline: "1-0", sampleCount: 914, unconditionalProbability: 0.0914, conditionalProbability: 0.1515, primarySettlement: "WIN" },
          { scoreline: "0-1", sampleCount: 841, unconditionalProbability: 0.0841, conditionalProbability: 0.1394, primarySettlement: "WIN" },
        ],
      },
    }),
    quiet({
      fixtureId: "1494217",
      kickoffUtc: "2026-07-25T15:30:00Z",
      status: "NS",
      competition: "瑞典超 · 常规赛第14轮",
      homeTeam: "北雪平",
      awayTeam: "米亚尔比",
      nextEvaluationAt: "2026-07-25T14:30:00Z",
      primaryMarketLabel: "优势不足",
      secondaryMarketLabel: null,
      scorelineSummary: null,
      quote: null,
      scorelineProjection: null,
    }, "NO_EDGE", "模型与市场差不足"),
    quiet({ fixtureId: "1494221", kickoffUtc: "2026-07-25T15:30:00Z", status: "NS", competition: "瑞典超 · 常规赛第14轮", homeTeam: "瓦纳默", awayTeam: "哈尔姆斯塔德", nextEvaluationAt: null, primaryMarketLabel: "优势不足", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "NO_EDGE", "模型与市场差不足"),
    quiet({ fixtureId: "1494224", kickoffUtc: "2026-07-24T17:00:00Z", status: "NS", competition: "瑞典超 · 常规赛第14轮", homeTeam: "奥斯达", awayTeam: "卡尔马", nextEvaluationAt: "2026-07-24T15:30:00Z", primaryMarketLabel: "等待临场盘口", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "NOT_READY", "临场赔率尚未齐全或已过期", "STALE"),
    quiet({ fixtureId: "el-001", kickoffUtc: "2026-07-25T17:00:00Z", status: "NS", competition: "挪威超 · 第15轮", homeTeam: "博德闪耀", awayTeam: "布兰", nextEvaluationAt: null, primaryMarketLabel: "优势不足", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "NO_EDGE", "优势不足"),
    quiet({ fixtureId: "el-002", kickoffUtc: "2026-07-26T15:00:00Z", status: "NS", competition: "挪威超 · 第15轮", homeTeam: "莫尔德", awayTeam: "罗森博格", nextEvaluationAt: null, primaryMarketLabel: "等待盘口", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "WATCH", "盘口未齐", "PARTIAL"),
    quiet({ fixtureId: "bra-001", kickoffUtc: "2026-07-26T22:30:00Z", status: "NS", competition: "巴甲 · 第16轮", homeTeam: "弗拉门戈", awayTeam: "帕尔梅拉斯", nextEvaluationAt: null, primaryMarketLabel: "等待盘口", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "NOT_READY", "赔率未返回", "BLOCKED"),
    quiet({ fixtureId: "csl-001", kickoffUtc: "2026-07-27T11:35:00Z", status: "NS", competition: "中超 · 第18轮", homeTeam: "上海海港", awayTeam: "成都蓉城", nextEvaluationAt: null, primaryMarketLabel: "优势不足", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "NO_EDGE", "优势不足"),
    quiet({ fixtureId: "csl-002", kickoffUtc: "2026-07-27T12:00:00Z", status: "NS", competition: "中超 · 第18轮", homeTeam: "北京国安", awayTeam: "山东泰山", nextEvaluationAt: null, primaryMarketLabel: "等待首发", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "WATCH", "首发未出", "PARTIAL"),
    quiet({ fixtureId: "bra-002", kickoffUtc: "2026-07-27T23:00:00Z", status: "NS", competition: "巴甲 · 第16轮", homeTeam: "克鲁塞罗", awayTeam: "米内罗竞技", nextEvaluationAt: null, primaryMarketLabel: "等待盘口", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "NOT_READY", "盘口未齐", "BLOCKED"),
    quiet({ fixtureId: "el-003", kickoffUtc: "2026-07-28T17:00:00Z", status: "NS", competition: "挪威超 · 第15轮", homeTeam: "维京", awayTeam: "特罗姆瑟", nextEvaluationAt: null, primaryMarketLabel: "优势不足", secondaryMarketLabel: null, scorelineSummary: null, quote: null, scorelineProjection: null }, "NO_EDGE", "优势不足"),
  ],
  leaguePerformance: [
    { league: "瑞典超", eligibleCount: 10, hitCount: 7, missCount: 2, pushCount: 1, clvMedian: -0.02, clvSampleCount: 1, statusLabel: "观察中" },
    { league: "挪威超", eligibleCount: 6, hitCount: 4, missCount: 1, pushCount: 1, clvMedian: 0.04, clvSampleCount: 1, statusLabel: "样本不足" },
  ],
};
