import type { MarketCode } from "../types/dashboard";

export const API_BASE = "/v1";
export const COMPETITION_ID = "1";

export const MARKET_ORDER: MarketCode[] = ["ASIAN_HANDICAP", "TOTALS", "FIRST_HALF_GOALS", "SCORE"];

export const MARKET_META: Record<MarketCode, { label: string; short: string; className: string }> = {
  ASIAN_HANDICAP: { label: "让球", short: "让球", className: "market-ah" },
  TOTALS: { label: "大小球", short: "大小", className: "market-ou" },
  FIRST_HALF_GOALS: { label: "半场进球", short: "半场", className: "market-half" },
  SCORE: { label: "比分", short: "比分", className: "market-score" },
};

export const INTENT_LABELS: Record<string, string> = {
  HOME_LEAN: "盘口偏移待验证",
  AWAY_LEAN: "盘口偏移待验证",
  OVER_LEAN: "盘口偏移待验证",
  UNDER_LEAN: "盘口偏移待验证",
  CONFLICTED: "信号分歧",
  INSUFFICIENT_DATA: "数据不足",
  LEAKAGE_BLOCKED: "赛前时间点拦截",
};

export const TENDENCY_LABELS: Record<string, string> = {
  HOME_AH: "让球方向待校准",
  AWAY_AH: "让球方向待校准",
  NO_SIDE_EDGE: "暂无边向",
  OVER: "大小球方向收起",
  UNDER: "大小球方向收起",
  "1H_OVER": "半场方向收起",
  "1H_UNDER": "半场谨慎",
  HOME: "赛果方向待校准",
  AWAY: "赛果方向待校准",
  DRAW: "赛果方向待校准",
};

export const COMPETITION_TRANSLATIONS: Array<[RegExp, string]> = [
  [/World Cup/i, "世界杯"],
  [/Group Stage\s*-\s*(\d+)/i, "小组赛第$1轮"],
  [/Group Stage/i, "小组赛"],
  [/Round of 16/i, "16 强"],
  [/Quarter[- ]final/i, "四分之一决赛"],
  [/Semi[- ]final/i, "半决赛"],
  [/Final/i, "决赛"],
];

export const TEAM_TRANSLATIONS: Record<string, string> = {
  Argentina: "阿根廷",
  Australia: "澳大利亚",
  Belgium: "比利时",
  Brazil: "巴西",
  "Burkina Faso": "布基纳法索",
  Cameroon: "喀麦隆",
  Canada: "加拿大",
  "Cape Verde": "佛得角",
  "Cape Verde Islands": "佛得角",
  Chile: "智利",
  China: "中国",
  Colombia: "哥伦比亚",
  "Costa Rica": "哥斯达黎加",
  Croatia: "克罗地亚",
  Denmark: "丹麦",
  Ecuador: "厄瓜多尔",
  Egypt: "埃及",
  England: "英格兰",
  France: "法国",
  Germany: "德国",
  Ghana: "加纳",
  Greece: "希腊",
  Honduras: "洪都拉斯",
  Iran: "伊朗",
  Iraq: "伊拉克",
  Italy: "意大利",
  Japan: "日本",
  Jordan: "约旦",
  Korea: "韩国",
  "Korea Republic": "韩国",
  Mexico: "墨西哥",
  Morocco: "摩洛哥",
  Netherlands: "荷兰",
  "New Zealand": "新西兰",
  Nigeria: "尼日利亚",
  Norway: "挪威",
  Panama: "巴拿马",
  Paraguay: "巴拉圭",
  Peru: "秘鲁",
  Poland: "波兰",
  Portugal: "葡萄牙",
  Qatar: "卡塔尔",
  Romania: "罗马尼亚",
  "Saudi Arabia": "沙特",
  Scotland: "苏格兰",
  Senegal: "塞内加尔",
  Serbia: "塞尔维亚",
  Spain: "西班牙",
  Sweden: "瑞典",
  Switzerland: "瑞士",
  Tunisia: "突尼斯",
  Turkey: "土耳其",
  Türkiye: "土耳其",
  Ukraine: "乌克兰",
  Uruguay: "乌拉圭",
  USA: "美国",
  "United States": "美国",
  Wales: "威尔士",
};

export const REASON_TRANSLATIONS: Array<[RegExp, string]> = [
  [/^F9_TRUE_XG:/, "滚动 xG 已纳入对比"],
  [/^F1_MARKET_MOVEMENT:/, "盘口从初盘到当前有可用变化"],
  [/^F2_BOOKMAKER_DISAGREEMENT:/, "多家庄家分歧已纳入"],
  [/^F3_REST:/, "体能与休息差已纳入"],
  [/^F4_MATCH_IMPORTANCE:/, "赛事阶段重要性已纳入"],
  [/^F5_SETTLED_AH_FORM:/, "近期赢盘表现已纳入"],
  [/^F6_H2H:/, "历史交锋已纳入"],
  [/^F7_STRENGTH_FORM:/, "球队强度与近期状态已纳入"],
  [/^F8_SQUAD_VALUE:/, "球队身价差异已纳入"],
  [/^FEATURES_INSUFFICIENT$/, "多因素输入不足"],
  [/^AH_ANALYSIS_INPUT_UNAVAILABLE$/, "让球分析输入不足"],
  [/^AH_MARKET_UNAVAILABLE$/, "让球盘口暂未覆盖"],
  [/^OU_ANALYSIS_INPUT_UNAVAILABLE$/, "大小球分析输入不足"],
  [/^OU_MARKET_UNAVAILABLE$/, "大小球盘口暂未覆盖"],
  [/^HALF_GOAL_INPUT_UNAVAILABLE$/, "半场进球模型输入不足"],
  [/^SCORE_MATRIX_UNAVAILABLE$/, "比分矩阵暂不可用"],
  [/^BOOKMAKER_INTENT_INPUT_UNAVAILABLE$/, "盘口假设输入不足"],
  [/^INSUFFICIENT_DATA$/, "数据点不足，暂不输出倾向"],
  [/^CONFLICTED$/, "盘口信号互相冲突，暂不强出方向"],
  [/^LEAKAGE_BLOCKED$/, "赛前时间点防泄漏规则拦截"],
  [/^大小球意图: OVER_LEAN$/, "大小球盘口假设未验证"],
  [/^大小球意图: UNDER_LEAN$/, "大小球盘口假设未验证"],
  [/^大小球意图: CONFLICTED$/, "大小球盘口方向存在分歧，暂不输出倾向"],
  [/^(?:庄家|盘口)意图: HOME_LEAN$/, "盘口假设未验证，暂不输出方向"],
  [/^(?:庄家|盘口)意图: AWAY_LEAN$/, "盘口假设未验证，暂不输出方向"],
  [/^半场 Poisson 拆分 P\(1H>0\.5\)=/, "半场进球使用 1H Poisson 拆分估计"],
  [/^比分使用方向一致条件概率/, "比分只展示与主方向一致的条件概率"],
  [/MISSING_XG/, "缺 xG"],
  [/MISSING_LINEUPS/, "缺首发"],
  [/MISSING_SCORE_MATRIX/, "缺比分矩阵"],
  [/MISSING_MARKET_OBSERVATIONS/, "缺盘口"],
  [/MISSING_BOOKMAKER_QUOTES/, "缺报价"],
  [/MISSING_MODEL_PROBABILITIES/, "缺模型概率"],
  [/MISSING_ODDS_TIMELINE/, "缺盘口快照"],
];
