import type { MarketCode } from "../types/dashboard";

export const API_BASE = "/v1";
export const COMPETITION_ID = "1";

export const CANONICAL_COMPETITION_LABELS: Record<string, string> = {
  allsvenskan: "瑞典超",
  argentina_primera: "阿甲",
  brasileirao_serie_a: "巴甲",
  bundesliga: "德甲",
  chinese_super_league: "中超",
  eliteserien: "挪威超",
  eredivisie: "荷甲",
  la_liga: "西甲",
  ligue_1: "法甲",
  mls: "美职联",
  premier_league: "英超",
  primeira_liga: "葡超",
  serie_a: "意甲",
  world_cup_2026: "世界杯",
};

export const MARKET_ORDER: MarketCode[] = ["ASIAN_HANDICAP", "TOTALS", "FIRST_HALF_GOALS", "SCORE"];

export const MARKET_META: Record<MarketCode, { label: string; short: string; className: string }> = {
  ASIAN_HANDICAP: { label: "让球", short: "让球", className: "market-ah" },
  TOTALS: { label: "大小球", short: "大小", className: "market-ou" },
  FIRST_HALF_GOALS: { label: "半场进球", short: "半场", className: "market-half" },
  SCORE: { label: "比分", short: "比分", className: "market-score" },
};

export const INTENT_LABELS: Record<string, string> = {
  HOME_LEAN: "盘口偏移待验证",
  AWAY_LEAN: "盘口偏移待验证",
  OVER_LEAN: "盘口偏移待验证",
  UNDER_LEAN: "盘口偏移待验证",
  CONFLICTED: "信号分歧",
  INSUFFICIENT_DATA: "数据不足",
  LEAKAGE_BLOCKED: "赛前时间点拦截",
};

export const TENDENCY_LABELS: Record<string, string> = {
  HOME_AH: "让球方向待校准",
  AWAY_AH: "让球方向待校准",
  NO_SIDE_EDGE: "暂无边向",
  OVER: "大小球方向收起",
  UNDER: "大小球方向收起",
  "1H_OVER": "半场方向收起",
  "1H_UNDER": "半场谨慎",
  HOME: "赛果方向待校准",
  AWAY: "赛果方向待校准",
  DRAW: "赛果方向待校准",
};

export const COMPETITION_NAME_LABELS: Record<string, string> = {
  Allsvenskan: "瑞典超",
  Bundesliga: "德甲",
  "Chinese Super League": "中超",
  Eliteserien: "挪威超",
  "La Liga": "西甲",
  "Premier League": "英超",
  "Primeira Liga": "葡超",
  "World Cup": "世界杯",
};

export const COMPETITION_STAGE_TRANSLATIONS: Array<[RegExp, string]> = [
  [/Regular Season\s*-\s*(\d+)/i, "常规赛第$1轮"],
  [/Group Stage\s*-\s*(\d+)/i, "小组赛第$1轮"],
  [/Group Stage/i, "小组赛"],
  [/Round of 16/i, "16 强"],
  [/Quarter[- ]finals?/i, "四分之一决赛"],
  [/Semi[- ]final/i, "半决赛"],
  [/Final/i, "决赛"],
];

export const PUBLIC_ENUM_LABELS: Record<string, string> = {
  AVAILABLE: "可用",
  AVAILABLE_WITH_GAPS: "部分可用",
  READY: "已就绪",
  PARTIAL: "部分就绪",
  BLOCKED: "仅赛程",
  STALE: "已过期",
  INSUFFICIENT: "证据不足",
  SAMPLE_BUILDING: "样本积累中",
  NOT_DEFINED: "尚未建立",
  NOT_PROVEN: "尚未证实",
  PAUSED_STALE: "证据过期，比较暂停",
  PRIOR_ONLY: "仅先验",
  UNAVAILABLE: "不可用",
  NOT_AVAILABLE: "暂不可用",
  NOT_READY: "尚未就绪",
  MARKET_NOT_READY: "市场证据未就绪",
  MODEL_NOT_READY: "模型尚未就绪",
  MODEL_CALIBRATION_NOT_READY: "模型校准尚未就绪",
  INSUFFICIENT_BOOKMAKER_DEPTH: "机构深度不足",
  MODEL_OUTSIDE_MARKET_RANGE: "模型区间外",
  MARKET_OUTSIDE_MODEL_RANGE: "市场区间外",
  COMPARABLE_WITHIN_MARKET_RANGE: "处于可比区间",
  OK: "正常",
  ATTENTION: "需关注",
  INCIDENT: "异常",
  UNASSESSED: "未评估",
};

export const PUBLIC_REASON_LABELS: Record<string, string> = {
  COLLECTION_INCIDENT: "采集异常",
  MARKET_MOVEMENT: "盘口或赔率变化",
  FRESH_MARKET_EVIDENCE: "市场证据完整",
  MODEL_DIAGNOSTIC: "模型诊断",
  STALE_MARKET_MEMORY: "证据已过期",
  DATA_INCOMPLETE: "数据链尚未齐全",
  CANDIDATE_INPUT_NOT_READY: "候选输入尚未完全就绪",
  LINEUP_PENDING: "首发等待",
  EXECUTABLE_CANDIDATE_QUOTE_NOT_READY: "精确候选报价尚未就绪",
  CANDIDATE_MODEL_NOT_READY: "候选模型输入尚未就绪",
  MARKET_EVIDENCE_NOT_CURRENT: "当前市场证据尚未就绪",
};

export const REASON_TRANSLATIONS: Array<[RegExp, string]> = [
  [/^DATA_FIELD_STALE$/, "数据字段已过期"],
  [/^DATA_IDENTITY_NOT_READY$/, "身份映射未就绪"],
  [/^DATA_MARKET_TIMELINE_INSUFFICIENT$/, "盘口时间线证据不足"],
  [/^DATA_REQUIRED_INPUT_MISSING$/, "缺少必要输入"],
  [/^DATA_STATUS_BLOCKED$/, "数据状态阻塞"],
  [/^MODEL_SIMULATION_NOT_READY$/, "模型模拟未就绪"],
  [/^LINEUPS_NOT_READY$/, "阵容信息未就绪"],
  [/^LINEUP_WINDOW_NOT_OPEN$/, "阵容公布窗口尚未开启"],
  [/^LINEUP_EXPECTED_BUT_ABSENT$/, "预计应有阵容信息，但来源仍为空"],
  [/^INJURIES_STALE$/, "伤停信息已过期"],
  [/^MARKET_STALE$/, "市场数据已过期"],
  [/^COLLECTION_PROVIDER_INCIDENT$/, "数据采集来源异常"],
  [/^EVIDENCE_READY$/, "证据已就绪"],
  [/^PRODUCT_AUTHORITY_DISABLED$/, "产品授权保持关闭"],
  [/^NO_TIMELINE_EVIDENCE$/, "暂无盘口时间线证据"],
  [/^ONE_OBSERVATION_NOT_A_TREND$/, "单次观测不构成趋势"],
  [/^DISCRETE_REAL_PATH$/, "真实离散盘口轨迹"],
  [/^([A-Z_]+)_FACTUAL_EVIDENCE$/, "已有对应事实证据"],
  [/^F9_TRUE_XG:/, "滚动 xG 已纳入对比"],
  [/^F1_MARKET_MOVEMENT:/, "盘口从初盘到当前有可用变化"],
  [/^F2_BOOKMAKER_DISAGREEMENT:/, "多家庄家分歧已纳入"],
  [/^F3_REST:/, "体能与休息差已纳入"],
  [/^F4_MATCH_IMPORTANCE:/, "赛事阶段重要性已纳入"],
  [/^F5_SETTLED_AH_FORM:/, "近期赢盘表现已纳入"],
  [/^F6_H2H:/, "历史交锋已纳入"],
  [/^F7_STRENGTH_FORM:/, "球队强度与近期状态已纳入"],
  [/^F8_SQUAD_VALUE:/, "球队身价差异已纳入"],
  [/^FEATURES_INSUFFICIENT$/, "多因素输入不足"],
  [/^AH_ANALYSIS_INPUT_UNAVAILABLE$/, "让球分析输入不足"],
  [/^AH_MARKET_UNAVAILABLE$/, "让球盘口暂未覆盖"],
  [/^OU_ANALYSIS_INPUT_UNAVAILABLE$/, "大小球分析输入不足"],
  [/^OU_MARKET_UNAVAILABLE$/, "大小球盘口暂未覆盖"],
  [/^HALF_GOAL_INPUT_UNAVAILABLE$/, "半场进球模型输入不足"],
  [/^SCORE_MATRIX_UNAVAILABLE$/, "比分矩阵暂不可用"],
  [/^BOOKMAKER_INTENT_INPUT_UNAVAILABLE$/, "盘口假设输入不足"],
  [/^INSUFFICIENT_DATA$/, "数据点不足，暂不输出倾向"],
  [/^CONFLICTED$/, "盘口信号互相冲突，暂不强出方向"],
  [/^LEAKAGE_BLOCKED$/, "赛前时间点防泄漏规则拦截"],
  [/^大小球意图: OVER_LEAN$/, "大小球盘口假设未验证"],
  [/^大小球意图: UNDER_LEAN$/, "大小球盘口假设未验证"],
  [/^大小球意图: CONFLICTED$/, "大小球盘口方向存在分歧，暂不输出倾向"],
  [/^(?:庄家|盘口)意图: HOME_LEAN$/, "盘口假设未验证，暂不输出方向"],
  [/^(?:庄家|盘口)意图: AWAY_LEAN$/, "盘口假设未验证，暂不输出方向"],
  [/^半场 Poisson 拆分 P\(1H>0\.5\)=/, "半场进球使用 1H Poisson 拆分估计"],
  [/^比分使用方向一致条件概率/, "比分只展示与主方向一致的条件概率"],
  [/MISSING_XG/, "缺 xG"],
  [/MISSING_LINEUPS/, "缺首发"],
  [/MISSING_SCORE_MATRIX/, "缺比分矩阵"],
  [/MISSING_MARKET_OBSERVATIONS/, "缺盘口"],
  [/MISSING_BOOKMAKER_QUOTES/, "缺报价"],
  [/MISSING_MODEL_PROBABILITIES/, "缺模型概率"],
  [/MISSING_ODDS_TIMELINE/, "缺盘口快照"],
];
